pipelines:
  branches:
    main: 
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - git push --mirror git@github.com:paras1805/practicejavaandroid.git